# Generated by Django 5.2.8 on 2025-11-09 03:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Toyota Land Cruiser V8', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=12)),
                ('seller_type', models.CharField(choices=[('private', 'Private Seller'), ('dealer', 'Dealer'), ('verified_dealer', 'Verified Dealer')], default='private', max_length=20)),
                ('condition_score', models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5.0', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('location', models.CharField(help_text='e.g., Nairobi, Kenya', max_length=255)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('drive', models.CharField(choices=[('2wd', '2WD'), ('4wd', '4WD'), ('awd', 'AWD'), ('fwd', 'FWD'), ('rwd', 'RWD')], help_text='Drive type', max_length=10)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in KM')),
                ('engine_size', models.PositiveIntegerField(help_text='Engine size in CC')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('plug_in_hybrid', 'Plug-in Hybrid')], max_length=20)),
                ('horse_power', models.PositiveIntegerField(blank=True, help_text='Engine power in HP', null=True)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-Automatic')], max_length=20)),
                ('torque', models.PositiveIntegerField(blank=True, help_text='Torque in Nm', null=True)),
                ('aspiration', models.CharField(blank=True, choices=[('naturally_aspirated', 'Naturally Aspirated'), ('turbo', 'Turbo'), ('twin_turbo', 'Twin Turbo'), ('supercharged', 'Supercharged')], max_length=30, null=True)),
                ('acceleration', models.DecimalField(blank=True, decimal_places=1, help_text='0-100 Kph in seconds', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.category')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['-is_primary', 'order', 'uploaded_at'],
                'unique_together': {('car', 'order')},
            },
        ),
    ]
